name 'winfirewall'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures winfirewall'
long_description 'Installs/Configures winfirewall'
version '0.3.0'
